apiVersion: v1
kind: Secret
metadata:
  name: [secretname]
  namespace: [namespace]
  annotations:
    kubernetes.io/service-account.name: [ServiceAccountName]
    kubernetes.io/service-account.uid: [ServiceAccountUID]
type: kubernetes.io/service-account-token
