apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: [name]
subjects:
- kind: Group
  name: system:masters
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: [ServiceAccountName]
  namespace: [ServiceAccountNameSpace]
roleRef:
  kind: ClusterRole
  name: [ClusterRoleName]
  apiGroup: rbac.authorization.k8s.io
